// WIP, THIS IS NOT FINAL!!

import java.util.Arrays;
public class Main {
public static void main(String[] args) {

// array
int[] teams = new int[12];
teams[0] = 108;
teams[1] = 180;
teams[2] = 116;
teams[3] = 254;
teams[4] = 162;
teams[5] = 200;
teams[6] = 302;
teams[7] = 386;
teams[8] = 100;
teams[9] = 962;

// loop
for (int numbers : teams) {
System.out.println(numbers);
         }
      }
   }
